import { mutation } from "./_generated/server";

// Seed is no longer needed - admins create codes from dashboard
// This file can be deleted or kept for reference
export default mutation({
  handler: async (ctx) => {
    return { 
      message: "Access codes are now generated by admins from the dashboard"
    };
  },
});
